//
// Agent.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct Agent: Codable {

    /** Unique identifier of this resource. Taken from the source system. */
    public let _id: Int

    /** REST API resource type or endpoint */
    public let apiModel: String

    /** REST API link for this resource */
    public let apiLink: String

    /** The name of this resource */
    public let title: String

    /** Sortable name for this agent, typically with last name first. */
    public let sortTitle: String?

    /** Alternate names for this agent */
    public let altTitles: [String]?

    /** The year this agent was born */
    public let birthDate: Int?

    /** Name of the place this agent was born */
    public let birthPlace: String?

    /** The year this agent died */
    public let deathDate: Int?

    /** Name of the place this agent died */
    public let deathPlace: String?

    /** A biographical description of the agent */
    public let _description: String?

    /** Unique identifier of this agent in Getty&#x27;s ULAN */
    public let ulanUri: String?

    /** Whether the use of the images of works by this artist are restricted by licensing */
    public let isLicensingRestricted: Bool

    /** Whether the agent is an artist. Solely based on whether the agent is listed as an artist for an artwork record. */
    public let isArtist: Bool

    /** Name of the type of agent, e.g. individual, fund, school, organization, etc. */
    public let agentTypeTitle: String?

    /** Unique identifier of the type of agent, e.g. individual, fund, school, organization, etc. */
    public let agentTypeId: Int?

    /** Unique identifiers of the works this artist created. */
    public let artworkIds: [Int]?

    /** Unique identifiers of the microsites this exhibition is a part of */
    public let siteIds: [Int]?

    /** Internal field to power the &#x60;/autocomplete&#x60; endpoint. Do not use directly. */
//    public let suggestAutocompleteBoosted: Any?

    /** Internal field to power the &#x60;/autosuggest&#x60; endpoint. Do not use directly. */
//    public let suggestAutocompleteAll: Any?

    /** Date and time the resource was updated in the source system */
    public let lastUpdatedSource: Date?

    /** Date and time the record was updated in the aggregator database */
    public let lastUpdated: Date?

    /** Date and time the record was updated in the aggregator search index */
    public let timestamp: Date?

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case apiModel = "api_model"
        case apiLink = "api_link"
        case title
        case sortTitle = "sort_title"
        case altTitles = "alt_titles"
        case birthDate = "birth_date"
        case birthPlace = "birth_place"
        case deathDate = "death_date"
        case deathPlace = "death_place"
        case _description = "description"
        case ulanUri = "ulan_uri"
        case isLicensingRestricted = "is_licensing_restricted"
        case isArtist = "is_artist"
        case agentTypeTitle = "agent_type_title"
        case agentTypeId = "agent_type_id"
        case artworkIds = "artwork_ids"
        case siteIds = "site_ids"
//        case suggestAutocompleteBoosted = "suggest_autocomplete_boosted"
//        case suggestAutocompleteAll = "suggest_autocomplete_all"
        case lastUpdatedSource = "last_updated_source"
        case lastUpdated = "last_updated"
        case timestamp
    }

}
