//
// Category.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct Category: Codable {

    /** Unique identifier of this resource. Taken from the source system. */
    public let _id: Int

    /** REST API resource type or endpoint */
    public let apiModel: String

    /** REST API link for this resource */
    public let apiLink: String

    /** The name of this resource */
    public let title: String

    /** URL to the shop page for this category */
    public let webUrl: String?

    /** Unique identifier of this category&#x27;s parent */
    public let parentId: Int?

    /** Name of this category&#x27;s parent */
    public let parentTitle: String?

    /** Unique identifiers of this category&#x27;s children */
    public let childIds: [Int]?

    /** Names of this category&#x27;s children */
    public let childTitles: [Int]?

    /** Date and time the resource was updated in the source system */
    public let lastUpdatedSource: Date?

    /** Date and time the record was updated in the aggregator database */
    public let lastUpdated: Date?

    /** Date and time the record was updated in the aggregator search index */
    public let timestamp: Date?

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case apiModel = "api_model"
        case apiLink = "api_link"
        case title
        case webUrl = "web_url"
        case parentId = "parent_id"
        case parentTitle = "parent_title"
        case childIds = "child_ids"
        case childTitles = "child_titles"
        case lastUpdatedSource = "last_updated_source"
        case lastUpdated = "last_updated"
        case timestamp
    }

}
