//
// EventOccurrence.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct EventOccurrence: Codable {

    /** Unique identifier of this resource. Taken from the source system. */
    public let _id: Int

    /** REST API resource type or endpoint */
    public let apiModel: String

    /** REST API link for this resource */
    public let apiLink: String

    /** The name of this resource */
    public let title: String

    /** Identifier of the master event of which this is an occurrence */
    public let eventId: Int?

    /** Brief description of the event */
    public let shortDescription: String?

    /** Description of the event */
    public let _description: String?

    /** The URL of an image representing this page */
    public let imageUrl: URL?

    /** Whether the event is private. Private events should be omitted from listings. */
    public let isPrivate: Bool?

    /** The date the event occurrence begins */
    public let startAt: Date?

    /** The date the event occurrence ends */
    public let endAt: Date?

    /** Where the event takes place */
    public let location: String?

    /** The URL to the sales site or an RSVP link for this event */
    public let buttonUrl: URL?

    /** The text used on the ticket/registration button */
    public let buttonText: String?

    /** Additional text below the ticket/registration button */
    public let buttonCaption: String?

    /** Date and time the resource was updated in the source system */
    public let lastUpdatedSource: Date?

    /** Date and time the record was updated in the aggregator database */
    public let lastUpdated: Date?

    /** Date and time the record was updated in the aggregator search index */
    public let timestamp: Date?

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case apiModel = "api_model"
        case apiLink = "api_link"
        case title
        case eventId = "event_id"
        case shortDescription = "short_description"
        case _description = "description"
        case imageUrl = "image_url"
        case isPrivate = "is_private"
        case startAt = "start_at"
        case endAt = "end_at"
        case location
        case buttonUrl = "button_url"
        case buttonText = "button_text"
        case buttonCaption = "button_caption"
        case lastUpdatedSource = "last_updated_source"
        case lastUpdated = "last_updated"
        case timestamp
    }

}
