//
// Exhibition.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct Exhibition: Codable {

    /** Unique identifier of this resource. Taken from the source system. */
    public let _id: Int

    /** REST API resource type or endpoint */
    public let apiModel: String

    /** REST API link for this resource */
    public let apiLink: String

    /** The name of this resource */
    public let title: String

    /** Identifier of the CITI exhibition this website exhibition is tied to */
    public let exhibitionId: Int?

    /** Is this exhibition currently featured on our website? */
    public let isFeatured: Bool?

    /** Is this exhibition currently published on our website? Only relevant for non-past exhibitions. */
    public let isPublished: Bool?

    /** The text at the top of the exhibition page */
    public let headerCopy: String?

    /** Short description to be used for exhibition listings */
    public let listDescription: String?

    /** Pricing or attendance information */
    public let exhibitionMessage: String?

    /** Date and time the resource was updated in the source system */
    public let lastUpdatedSource: Date?

    /** Date and time the record was updated in the aggregator database */
    public let lastUpdated: Date?

    /** Date and time the record was updated in the aggregator search index */
    public let timestamp: Date?

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case apiModel = "api_model"
        case apiLink = "api_link"
        case title
        case exhibitionId = "exhibition_id"
        case isFeatured = "is_featured"
        case isPublished = "is_published"
        case headerCopy = "header_copy"
        case listDescription = "list_description"
        case exhibitionMessage = "exhibition_message"
        case lastUpdatedSource = "last_updated_source"
        case lastUpdated = "last_updated"
        case timestamp
    }

}
