//
// Gallery.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct Gallery: Codable {

    /** Unique identifier of this resource. Taken from the source system. */
    public let _id: Int

    /** REST API resource type or endpoint */
    public let apiModel: String

    /** REST API link for this resource */
    public let apiLink: String

    /** The name of this resource */
    public let title: String

    /** Type always takes one of the following values: AIC Gallery, AIC Storage, No location */
    public let type: String?

    /** Whether the gallery is currently closed */
    public let isClosed: Bool?

    /** The gallery&#x27;s room number. For \&quot;Gallery 100A\&quot;, this would be \&quot;100A\&quot;. */
    public let number: String?

    /** The level the gallery is on, e.g., 1, 2, 3, or LL */
    public let floor: String?

    /** Latitude coordinate of the center of the room */
    public let latitude: Double?

    /** Longitude coordinate of the center of the room */
    public let longitude: Double?

    /** Latitude and longitude coordinates of the center of the room */
    public let latlon: String?

    /** Date and time the resource was updated in the source system */
    public let lastUpdatedSource: Date?

    /** Date and time the record was updated in the aggregator database */
    public let lastUpdated: Date?

    /** Date and time the record was updated in the aggregator search index */
    public let timestamp: Date?

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case apiModel = "api_model"
        case apiLink = "api_link"
        case title
        case type
        case isClosed = "is_closed"
        case number
        case floor
        case latitude
        case longitude
        case latlon
        case lastUpdatedSource = "last_updated_source"
        case lastUpdated = "last_updated"
        case timestamp
    }

}
