//
// ModelError.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct ModelError: Codable {

    public let status: Int
    public let error: String
    public let detail: String

    public init(status: Int, error: String, detail: String) { 
        self.status = status
        self.error = error
        self.detail = detail
    }

}
