//
// SearchResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct SearchResult: Codable {


    /** Search index ranking of the result */
    public let score: Double?

    /** Unique identifier within the search index */
    public let _id: Int

    /** API unique identifier */
    public let apiId: String?

    /** Name of the model the resource represents */
    public let apiModel: String

    /** URL to this recource in the API */
    public let apiLink: String

    /** The name of this resource */
    public let title: String

    /** Date this record was last updated in the API */
    public let timestamp: Date?

    /** Whether this record has been flagged to be boosted */
    public let isBoosted: Bool

    /** Metadata on the image representing this record */
    public let thumbnail: [Thumbnail]?
    
    public enum CodingKeys: String, CodingKey { 
        case score = "_score"
        case _id = "id"
        case apiId = "api_id"
        case apiModel = "api_model"
        case apiLink = "api_link"
        case title
        case timestamp
        case isBoosted = "is_boosted"
        case thumbnail
    }

}
