//
// Site.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct Site: Codable {

    /** Unique identifier of this resource. Taken from the source system. */
    public let _id: Int

    /** REST API resource type or endpoint */
    public let apiModel: String

    /** REST API link for this resource */
    public let apiLink: String

    /** The name of this resource */
    public let title: String

    /** Explanation of what this site is */
    public let _description: String?

    /** URL to this site */
    public let webUrl: String?

    /** Unique identifier of the exhibitions this site is associated with */
    public let exhibitionIds: [Int]?

    /** Names of the exhibitions this site is associated with */
    public let exhibitionTitles: [String]?

    /** Unique identifiers of the artists this site is associated with */
    public let artistIds: [Int]?

    /** Names of the artists this site is associated with */
    public let artistTitles: [String]?

    /** Unique identifiers of the artworks this site is associated with */
    public let artworkIds: [Int]?

    /** Names of the artworks this site is associated with */
    public let artworkTitles: [String]?

    /** Date and time the resource was updated in the source system */
    public let lastUpdatedSource: Date?

    /** Date and time the record was updated in the aggregator database */
    public let lastUpdated: Date?

    /** Date and time the record was updated in the aggregator search index */
    public let timestamp: Date?

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case apiModel = "api_model"
        case apiLink = "api_link"
        case title
        case _description = "description"
        case webUrl = "web_url"
        case exhibitionIds = "exhibition_ids"
        case exhibitionTitles = "exhibition_titles"
        case artistIds = "artist_ids"
        case artistTitles = "artist_titles"
        case artworkIds = "artwork_ids"
        case artworkTitles = "artwork_titles"
        case lastUpdatedSource = "last_updated_source"
        case lastUpdated = "last_updated"
        case timestamp
    }

}
