//
// Tour.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct Tour: Codable {

    /** Unique identifier of this resource. Taken from the source system. */
    public let _id: Int

    /** REST API resource type or endpoint */
    public let apiModel: String

    /** REST API link for this resource */
    public let apiLink: String

    /** The name of this resource */
    public let title: String

    /** The main image for the tour */
    public let image: Data?

    /** Explanation of what the tour is */
    public let _description: String?

    /** Text introducing the tour */
    public let intro: String?

    /** Number representing this tour&#x27;s sort order */
    public let weight: Double?

    /** Link to the audio file of the introduction */
    public let introLink: URL?

    /** Transcript of the introduction audio to the tour */
    public let introTranscript: String?

    /** Names of the artworks featured in this tour&#x27;s tour stops */
    public let artworkTitles: [String]?

    /** Names of the artists of the artworks featured in this tour&#x27;s tour stops */
    public let artistTitles: [String]?

    /** Date and time the resource was updated in the source system */
    public let lastUpdatedSource: Date?

    /** Date and time the record was updated in the aggregator database */
    public let lastUpdated: Date?

    /** Date and time the record was updated in the aggregator search index */
    public let timestamp: Date?

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case apiModel = "api_model"
        case apiLink = "api_link"
        case title
        case image
        case _description = "description"
        case intro
        case weight
        case introLink = "intro_link"
        case introTranscript = "intro_transcript"
        case artworkTitles = "artwork_titles"
        case artistTitles = "artist_titles"
        case lastUpdatedSource = "last_updated_source"
        case lastUpdated = "last_updated"
        case timestamp
    }

}
