//
// AssetsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class AssetsAPI {
    /**
     A list of all assets sorted by last updated date in descending order.

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func assetsGet(completion: @escaping ((_ data: [Asset]?,_ error: Error?) -> Void)) {
        assetsGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     A list of all assets sorted by last updated date in descending order.
     - GET /assets
     - examples: [{contentType=application/json, example=[ {
  "last_updated" : { },
  "is_multimedia_resource" : { },
  "lake_guid" : { },
  "description" : { },
  "suggest_autocomplete_all" : { },
  "title" : { },
  "type" : { },
  "content" : { },
  "content_e_tag" : { },
  "suggest_autocomplete_boosted" : { },
  "api_model" : { },
  "copyright_notice" : { },
  "alt_text" : { },
  "api_link" : { },
  "artwork_titles" : { },
  "content_modified_at" : { },
  "artwork_ids" : { },
  "id" : { },
  "is_educational_resource" : { },
  "last_updated_source" : { },
  "is_teacher_resource" : { },
  "timestamp" : { }
}, {
  "last_updated" : { },
  "is_multimedia_resource" : { },
  "lake_guid" : { },
  "description" : { },
  "suggest_autocomplete_all" : { },
  "title" : { },
  "type" : { },
  "content" : { },
  "content_e_tag" : { },
  "suggest_autocomplete_boosted" : { },
  "api_model" : { },
  "copyright_notice" : { },
  "alt_text" : { },
  "api_link" : { },
  "artwork_titles" : { },
  "content_modified_at" : { },
  "artwork_ids" : { },
  "id" : { },
  "is_educational_resource" : { },
  "last_updated_source" : { },
  "is_teacher_resource" : { },
  "timestamp" : { }
} ]}]

     - returns: RequestBuilder<[Asset]> 
     */
    open class func assetsGetWithRequestBuilder() -> RequestBuilder<[Asset]> {
        let path = "/assets"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[Asset]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     A single asset by the given identifier. {id} is the identifier from our collections management system.
     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func assetsIdGet(_id: String, completion: @escaping ((_ data: [Asset]?,_ error: Error?) -> Void)) {
        assetsIdGetWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     A single asset by the given identifier. {id} is the identifier from our collections management system.
     - GET /assets/{id}
     - examples: [{contentType=application/json, example=[ {
  "last_updated" : { },
  "is_multimedia_resource" : { },
  "lake_guid" : { },
  "description" : { },
  "suggest_autocomplete_all" : { },
  "title" : { },
  "type" : { },
  "content" : { },
  "content_e_tag" : { },
  "suggest_autocomplete_boosted" : { },
  "api_model" : { },
  "copyright_notice" : { },
  "alt_text" : { },
  "api_link" : { },
  "artwork_titles" : { },
  "content_modified_at" : { },
  "artwork_ids" : { },
  "id" : { },
  "is_educational_resource" : { },
  "last_updated_source" : { },
  "is_teacher_resource" : { },
  "timestamp" : { }
}, {
  "last_updated" : { },
  "is_multimedia_resource" : { },
  "lake_guid" : { },
  "description" : { },
  "suggest_autocomplete_all" : { },
  "title" : { },
  "type" : { },
  "content" : { },
  "content_e_tag" : { },
  "suggest_autocomplete_boosted" : { },
  "api_model" : { },
  "copyright_notice" : { },
  "alt_text" : { },
  "api_link" : { },
  "artwork_titles" : { },
  "content_modified_at" : { },
  "artwork_ids" : { },
  "id" : { },
  "is_educational_resource" : { },
  "last_updated_source" : { },
  "is_teacher_resource" : { },
  "timestamp" : { }
} ]}]
     - parameter _id: (path)  

     - returns: RequestBuilder<[Asset]> 
     */
    open class func assetsIdGetWithRequestBuilder(_id: String) -> RequestBuilder<[Asset]> {
        var path = "/assets/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[Asset]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
