//
// EventsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class EventsAPI {
    /**
     A list of all events sorted by last updated date in descending order.

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func eventsGet(completion: @escaping ((_ data: [Event]?,_ error: Error?) -> Void)) {
        eventsGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     A list of all events sorted by last updated date in descending order.
     - GET /events
     - examples: [{contentType=application/json, example=[ {
  "event_host_id" : { },
  "is_ticketed" : { },
  "search_tags" : { },
  "suggest_autocomplete_all" : { },
  "event_type_id" : { },
  "door_time" : { },
  "alt_event_type_ids" : { },
  "ticketed_event_id" : { },
  "id" : { },
  "entrance" : { },
  "last_updated_source" : { },
  "slug" : { },
  "join_url" : { },
  "last_updated" : { },
  "is_admission_required" : { },
  "image_url" : { },
  "alt_audience_ids" : { },
  "published" : { },
  "publish_end_date" : { },
  "start_time" : { },
  "rsvp_link" : { },
  "buy_button_caption" : { },
  "suggest_autocomplete_boosted" : { },
  "buy_button_text" : { },
  "show_presented_by" : { },
  "date_display" : { },
  "program_ids" : { },
  "is_member_exclusive" : { },
  "is_private" : { },
  "end_date" : { },
  "event_host_title" : { },
  "short_description" : { },
  "is_after_hours" : { },
  "description" : { },
  "layout_type" : { },
  "audience_id" : { },
  "title" : { },
  "survey_url" : { },
  "title_display" : { },
  "api_link" : { },
  "start_date" : { },
  "timestamp" : { },
  "hero_caption" : { },
  "is_registration_required" : { },
  "end_time" : { },
  "sponsor_id" : { },
  "list_description" : { },
  "test_emails" : { },
  "api_model" : { },
  "header_description" : { },
  "publish_start_date" : { },
  "is_free" : { },
  "program_titles" : { },
  "location" : { },
  "is_sold_out" : { }
}, {
  "event_host_id" : { },
  "is_ticketed" : { },
  "search_tags" : { },
  "suggest_autocomplete_all" : { },
  "event_type_id" : { },
  "door_time" : { },
  "alt_event_type_ids" : { },
  "ticketed_event_id" : { },
  "id" : { },
  "entrance" : { },
  "last_updated_source" : { },
  "slug" : { },
  "join_url" : { },
  "last_updated" : { },
  "is_admission_required" : { },
  "image_url" : { },
  "alt_audience_ids" : { },
  "published" : { },
  "publish_end_date" : { },
  "start_time" : { },
  "rsvp_link" : { },
  "buy_button_caption" : { },
  "suggest_autocomplete_boosted" : { },
  "buy_button_text" : { },
  "show_presented_by" : { },
  "date_display" : { },
  "program_ids" : { },
  "is_member_exclusive" : { },
  "is_private" : { },
  "end_date" : { },
  "event_host_title" : { },
  "short_description" : { },
  "is_after_hours" : { },
  "description" : { },
  "layout_type" : { },
  "audience_id" : { },
  "title" : { },
  "survey_url" : { },
  "title_display" : { },
  "api_link" : { },
  "start_date" : { },
  "timestamp" : { },
  "hero_caption" : { },
  "is_registration_required" : { },
  "end_time" : { },
  "sponsor_id" : { },
  "list_description" : { },
  "test_emails" : { },
  "api_model" : { },
  "header_description" : { },
  "publish_start_date" : { },
  "is_free" : { },
  "program_titles" : { },
  "location" : { },
  "is_sold_out" : { }
} ]}]

     - returns: RequestBuilder<[Event]> 
     */
    open class func eventsGetWithRequestBuilder() -> RequestBuilder<[Event]> {
        let path = "/events"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[Event]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     A single event by the given identifier.
     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func eventsIdGet(_id: String, completion: @escaping ((_ data: [Event]?,_ error: Error?) -> Void)) {
        eventsIdGetWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     A single event by the given identifier.
     - GET /events/{id}
     - examples: [{contentType=application/json, example=[ {
  "event_host_id" : { },
  "is_ticketed" : { },
  "search_tags" : { },
  "suggest_autocomplete_all" : { },
  "event_type_id" : { },
  "door_time" : { },
  "alt_event_type_ids" : { },
  "ticketed_event_id" : { },
  "id" : { },
  "entrance" : { },
  "last_updated_source" : { },
  "slug" : { },
  "join_url" : { },
  "last_updated" : { },
  "is_admission_required" : { },
  "image_url" : { },
  "alt_audience_ids" : { },
  "published" : { },
  "publish_end_date" : { },
  "start_time" : { },
  "rsvp_link" : { },
  "buy_button_caption" : { },
  "suggest_autocomplete_boosted" : { },
  "buy_button_text" : { },
  "show_presented_by" : { },
  "date_display" : { },
  "program_ids" : { },
  "is_member_exclusive" : { },
  "is_private" : { },
  "end_date" : { },
  "event_host_title" : { },
  "short_description" : { },
  "is_after_hours" : { },
  "description" : { },
  "layout_type" : { },
  "audience_id" : { },
  "title" : { },
  "survey_url" : { },
  "title_display" : { },
  "api_link" : { },
  "start_date" : { },
  "timestamp" : { },
  "hero_caption" : { },
  "is_registration_required" : { },
  "end_time" : { },
  "sponsor_id" : { },
  "list_description" : { },
  "test_emails" : { },
  "api_model" : { },
  "header_description" : { },
  "publish_start_date" : { },
  "is_free" : { },
  "program_titles" : { },
  "location" : { },
  "is_sold_out" : { }
}, {
  "event_host_id" : { },
  "is_ticketed" : { },
  "search_tags" : { },
  "suggest_autocomplete_all" : { },
  "event_type_id" : { },
  "door_time" : { },
  "alt_event_type_ids" : { },
  "ticketed_event_id" : { },
  "id" : { },
  "entrance" : { },
  "last_updated_source" : { },
  "slug" : { },
  "join_url" : { },
  "last_updated" : { },
  "is_admission_required" : { },
  "image_url" : { },
  "alt_audience_ids" : { },
  "published" : { },
  "publish_end_date" : { },
  "start_time" : { },
  "rsvp_link" : { },
  "buy_button_caption" : { },
  "suggest_autocomplete_boosted" : { },
  "buy_button_text" : { },
  "show_presented_by" : { },
  "date_display" : { },
  "program_ids" : { },
  "is_member_exclusive" : { },
  "is_private" : { },
  "end_date" : { },
  "event_host_title" : { },
  "short_description" : { },
  "is_after_hours" : { },
  "description" : { },
  "layout_type" : { },
  "audience_id" : { },
  "title" : { },
  "survey_url" : { },
  "title_display" : { },
  "api_link" : { },
  "start_date" : { },
  "timestamp" : { },
  "hero_caption" : { },
  "is_registration_required" : { },
  "end_time" : { },
  "sponsor_id" : { },
  "list_description" : { },
  "test_emails" : { },
  "api_model" : { },
  "header_description" : { },
  "publish_start_date" : { },
  "is_free" : { },
  "program_titles" : { },
  "location" : { },
  "is_sold_out" : { }
} ]}]
     - parameter _id: (path)  

     - returns: RequestBuilder<[Event]> 
     */
    open class func eventsIdGetWithRequestBuilder(_id: String) -> RequestBuilder<[Event]> {
        var path = "/events/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[Event]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Search events data in the aggregator. 
     - parameter q: (query) Your search query (optional)     - parameter query: (query) For complex queries, you can pass Elasticsearch domain syntax queries here (optional)     - parameter sort: (query) Used in conjunction with &#x60;query&#x60; (optional)     - parameter from: (query) Starting point of results. Pagination via Elasticsearch conventions (optional)     - parameter size: (query) Number of results to return. Pagination via Elasticsearch conventions (optional)     - parameter facets: (query) A comma-separated list of &#x27;count&#x27; aggregation facets to include in the results. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func eventsSearchGet(q: String? = nil, query: String? = nil, sort: String? = nil, from: Int? = nil, size: Int? = nil, facets: String? = nil, completion: @escaping ((_ data: [SearchResult]?,_ error: Error?) -> Void)) {
        eventsSearchGetWithRequestBuilder(q: q, query: query, sort: sort, from: from, size: size, facets: facets).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Search events data in the aggregator. 
     - GET /events/search
     - examples: [{contentType=application/json, example=[ {
  "api_id" : { },
  "thumbnail" : { },
  "api_model" : { },
  "is_boosted" : { },
  "api_link" : { },
  "id" : { },
  "_score" : { },
  "title" : { },
  "timestamp" : { }
}, {
  "api_id" : { },
  "thumbnail" : { },
  "api_model" : { },
  "is_boosted" : { },
  "api_link" : { },
  "id" : { },
  "_score" : { },
  "title" : { },
  "timestamp" : { }
} ]}]
     - parameter q: (query) Your search query (optional)     - parameter query: (query) For complex queries, you can pass Elasticsearch domain syntax queries here (optional)     - parameter sort: (query) Used in conjunction with &#x60;query&#x60; (optional)     - parameter from: (query) Starting point of results. Pagination via Elasticsearch conventions (optional)     - parameter size: (query) Number of results to return. Pagination via Elasticsearch conventions (optional)     - parameter facets: (query) A comma-separated list of &#x27;count&#x27; aggregation facets to include in the results. (optional)

     - returns: RequestBuilder<[SearchResult]> 
     */
    open class func eventsSearchGetWithRequestBuilder(q: String? = nil, query: String? = nil, sort: String? = nil, from: Int? = nil, size: Int? = nil, facets: String? = nil) -> RequestBuilder<[SearchResult]> {
        let path = "/events/search"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "q": q, 
                        "query": query, 
                        "sort": sort, 
                        "from": from, 
                        "size": size, 
                        "facets": facets
        ])

        let requestBuilder: RequestBuilder<[SearchResult]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
