//
// EventOccurrencesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class EventOccurrencesAPI {
    /**
     A list of all event-occurrences sorted by last updated date in descending order.

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func eventOccurrencesGet(completion: @escaping ((_ data: [EventOccurrence]?,_ error: Error?) -> Void)) {
        eventOccurrencesGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }
    /**
     A list of all event-occurrences sorted by last updated date in descending order.
     - GET /event-occurrences
     - examples: [{contentType=application/json, example=[ {
  "is_private" : { },
  "short_description" : { },
  "end_at" : { },
  "last_updated" : { },
  "image_url" : { },
  "button_url" : { },
  "description" : { },
  "suggest_autocomplete_all" : { },
  "title" : { },
  "start_at" : { },
  "button_caption" : { },
  "event_id" : { },
  "suggest_autocomplete_boosted" : { },
  "api_model" : { },
  "api_link" : { },
  "location" : { },
  "id" : { },
  "button_text" : { },
  "last_updated_source" : { },
  "timestamp" : { }
}, {
  "is_private" : { },
  "short_description" : { },
  "end_at" : { },
  "last_updated" : { },
  "image_url" : { },
  "button_url" : { },
  "description" : { },
  "suggest_autocomplete_all" : { },
  "title" : { },
  "start_at" : { },
  "button_caption" : { },
  "event_id" : { },
  "suggest_autocomplete_boosted" : { },
  "api_model" : { },
  "api_link" : { },
  "location" : { },
  "id" : { },
  "button_text" : { },
  "last_updated_source" : { },
  "timestamp" : { }
} ]}]

     - returns: RequestBuilder<[EventOccurrence]> 
     */
    open class func eventOccurrencesGetWithRequestBuilder() -> RequestBuilder<[EventOccurrence]> {
        let path = "/event-occurrences"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[EventOccurrence]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     A single event-occurrence by the given identifier.
     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func eventOccurrencesIdGet(_id: String, completion: @escaping ((_ data: [EventOccurrence]?,_ error: Error?) -> Void)) {
        eventOccurrencesIdGetWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     A single event-occurrence by the given identifier.
     - GET /event-occurrences/{id}
     - examples: [{contentType=application/json, example=[ {
  "is_private" : { },
  "short_description" : { },
  "end_at" : { },
  "last_updated" : { },
  "image_url" : { },
  "button_url" : { },
  "description" : { },
  "suggest_autocomplete_all" : { },
  "title" : { },
  "start_at" : { },
  "button_caption" : { },
  "event_id" : { },
  "suggest_autocomplete_boosted" : { },
  "api_model" : { },
  "api_link" : { },
  "location" : { },
  "id" : { },
  "button_text" : { },
  "last_updated_source" : { },
  "timestamp" : { }
}, {
  "is_private" : { },
  "short_description" : { },
  "end_at" : { },
  "last_updated" : { },
  "image_url" : { },
  "button_url" : { },
  "description" : { },
  "suggest_autocomplete_all" : { },
  "title" : { },
  "start_at" : { },
  "button_caption" : { },
  "event_id" : { },
  "suggest_autocomplete_boosted" : { },
  "api_model" : { },
  "api_link" : { },
  "location" : { },
  "id" : { },
  "button_text" : { },
  "last_updated_source" : { },
  "timestamp" : { }
} ]}]
     - parameter _id: (path)  

     - returns: RequestBuilder<[EventOccurrence]> 
     */
    open class func eventOccurrencesIdGetWithRequestBuilder(_id: String) -> RequestBuilder<[EventOccurrence]> {
        var path = "/event-occurrences/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[EventOccurrence]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Search event-occurrences data in the aggregator. 
     - parameter q: (query) Your search query (optional)     - parameter query: (query) For complex queries, you can pass Elasticsearch domain syntax queries here (optional)     - parameter sort: (query) Used in conjunction with &#x60;query&#x60; (optional)     - parameter from: (query) Starting point of results. Pagination via Elasticsearch conventions (optional)     - parameter size: (query) Number of results to return. Pagination via Elasticsearch conventions (optional)     - parameter facets: (query) A comma-separated list of &#x27;count&#x27; aggregation facets to include in the results. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func eventOccurrencesSearchGet(q: String? = nil, query: String? = nil, sort: String? = nil, from: Int? = nil, size: Int? = nil, facets: String? = nil, completion: @escaping ((_ data: [SearchResult]?,_ error: Error?) -> Void)) {
        eventOccurrencesSearchGetWithRequestBuilder(q: q, query: query, sort: sort, from: from, size: size, facets: facets).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Search event-occurrences data in the aggregator. 
     - GET /event-occurrences/search
     - examples: [{contentType=application/json, example=[ {
  "api_id" : { },
  "thumbnail" : { },
  "api_model" : { },
  "is_boosted" : { },
  "api_link" : { },
  "id" : { },
  "_score" : { },
  "title" : { },
  "timestamp" : { }
}, {
  "api_id" : { },
  "thumbnail" : { },
  "api_model" : { },
  "is_boosted" : { },
  "api_link" : { },
  "id" : { },
  "_score" : { },
  "title" : { },
  "timestamp" : { }
} ]}]
     - parameter q: (query) Your search query (optional)     - parameter query: (query) For complex queries, you can pass Elasticsearch domain syntax queries here (optional)     - parameter sort: (query) Used in conjunction with &#x60;query&#x60; (optional)     - parameter from: (query) Starting point of results. Pagination via Elasticsearch conventions (optional)     - parameter size: (query) Number of results to return. Pagination via Elasticsearch conventions (optional)     - parameter facets: (query) A comma-separated list of &#x27;count&#x27; aggregation facets to include in the results. (optional)

     - returns: RequestBuilder<[SearchResult]> 
     */
    open class func eventOccurrencesSearchGetWithRequestBuilder(q: String? = nil, query: String? = nil, sort: String? = nil, from: Int? = nil, size: Int? = nil, facets: String? = nil) -> RequestBuilder<[SearchResult]> {
        let path = "/event-occurrences/search"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "q": q, 
                        "query": query, 
                        "sort": sort, 
                        "from": from, 
                        "size": size, 
                        "facets": facets
        ])

        let requestBuilder: RequestBuilder<[SearchResult]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
