//
// GalleriesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class GalleriesAPI {
    /**
     A list of all galleries sorted by last updated date in descending order.

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func galleriesGet(completion: @escaping ((_ data: [Gallery]?,_ error: Error?) -> Void)) {
        galleriesGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     A list of all galleries sorted by last updated date in descending order.
     - GET /galleries
     - examples: [{contentType=application/json, example=[ {
  "last_updated" : { },
  "latitude" : { },
  "suggest_autocomplete_all" : { },
  "title" : { },
  "type" : { },
  "number" : { },
  "suggest_autocomplete_boosted" : { },
  "api_model" : { },
  "latlon" : { },
  "api_link" : { },
  "id" : { },
  "floor" : { },
  "last_updated_source" : { },
  "is_closed" : { },
  "longitude" : { },
  "timestamp" : { }
}, {
  "last_updated" : { },
  "latitude" : { },
  "suggest_autocomplete_all" : { },
  "title" : { },
  "type" : { },
  "number" : { },
  "suggest_autocomplete_boosted" : { },
  "api_model" : { },
  "latlon" : { },
  "api_link" : { },
  "id" : { },
  "floor" : { },
  "last_updated_source" : { },
  "is_closed" : { },
  "longitude" : { },
  "timestamp" : { }
} ]}]

     - returns: RequestBuilder<[Gallery]> 
     */
    open class func galleriesGetWithRequestBuilder() -> RequestBuilder<[Gallery]> {
        let path = "/galleries"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[Gallery]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     A single gallery by the given identifier. {id} is the identifier from our collections management system.
     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func galleriesIdGet(_id: String, completion: @escaping ((_ data: [Gallery]?,_ error: Error?) -> Void)) {
        galleriesIdGetWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     A single gallery by the given identifier. {id} is the identifier from our collections management system.
     - GET /galleries/{id}
     - examples: [{contentType=application/json, example=[ {
  "last_updated" : { },
  "latitude" : { },
  "suggest_autocomplete_all" : { },
  "title" : { },
  "type" : { },
  "number" : { },
  "suggest_autocomplete_boosted" : { },
  "api_model" : { },
  "latlon" : { },
  "api_link" : { },
  "id" : { },
  "floor" : { },
  "last_updated_source" : { },
  "is_closed" : { },
  "longitude" : { },
  "timestamp" : { }
}, {
  "last_updated" : { },
  "latitude" : { },
  "suggest_autocomplete_all" : { },
  "title" : { },
  "type" : { },
  "number" : { },
  "suggest_autocomplete_boosted" : { },
  "api_model" : { },
  "latlon" : { },
  "api_link" : { },
  "id" : { },
  "floor" : { },
  "last_updated_source" : { },
  "is_closed" : { },
  "longitude" : { },
  "timestamp" : { }
} ]}]
     - parameter _id: (path)  

     - returns: RequestBuilder<[Gallery]> 
     */
    open class func galleriesIdGetWithRequestBuilder(_id: String) -> RequestBuilder<[Gallery]> {
        var path = "/galleries/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[Gallery]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Search galleries data in the aggregator. 
     - parameter q: (query) Your search query (optional)     - parameter query: (query) For complex queries, you can pass Elasticsearch domain syntax queries here (optional)     - parameter sort: (query) Used in conjunction with &#x60;query&#x60; (optional)     - parameter from: (query) Starting point of results. Pagination via Elasticsearch conventions (optional)     - parameter size: (query) Number of results to return. Pagination via Elasticsearch conventions (optional)     - parameter facets: (query) A comma-separated list of &#x27;count&#x27; aggregation facets to include in the results. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func galleriesSearchGet(q: String? = nil, query: String? = nil, sort: String? = nil, from: Int? = nil, size: Int? = nil, facets: String? = nil, completion: @escaping ((_ data: [SearchResult]?,_ error: Error?) -> Void)) {
        galleriesSearchGetWithRequestBuilder(q: q, query: query, sort: sort, from: from, size: size, facets: facets).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Search galleries data in the aggregator. 
     - GET /galleries/search
     - examples: [{contentType=application/json, example=[ {
  "api_id" : { },
  "thumbnail" : { },
  "api_model" : { },
  "is_boosted" : { },
  "api_link" : { },
  "id" : { },
  "_score" : { },
  "title" : { },
  "timestamp" : { }
}, {
  "api_id" : { },
  "thumbnail" : { },
  "api_model" : { },
  "is_boosted" : { },
  "api_link" : { },
  "id" : { },
  "_score" : { },
  "title" : { },
  "timestamp" : { }
} ]}]
     - parameter q: (query) Your search query (optional)     - parameter query: (query) For complex queries, you can pass Elasticsearch domain syntax queries here (optional)     - parameter sort: (query) Used in conjunction with &#x60;query&#x60; (optional)     - parameter from: (query) Starting point of results. Pagination via Elasticsearch conventions (optional)     - parameter size: (query) Number of results to return. Pagination via Elasticsearch conventions (optional)     - parameter facets: (query) A comma-separated list of &#x27;count&#x27; aggregation facets to include in the results. (optional)

     - returns: RequestBuilder<[SearchResult]> 
     */
    open class func galleriesSearchGetWithRequestBuilder(q: String? = nil, query: String? = nil, sort: String? = nil, from: Int? = nil, size: Int? = nil, facets: String? = nil) -> RequestBuilder<[SearchResult]> {
        let path = "/galleries/search"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "q": q, 
                        "query": query, 
                        "sort": sort, 
                        "from": from, 
                        "size": size, 
                        "facets": facets
        ])

        let requestBuilder: RequestBuilder<[SearchResult]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
