//
// ProductsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class ProductsAPI {
    /**
     A list of all products sorted by last updated date in descending order.

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func productsGet(completion: @escaping ((_ data: [Product]?,_ error: Error?) -> Void)) {
        productsGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     A list of all products sorted by last updated date in descending order.
     - GET /products
     - examples: [{contentType=application/json, example=[ {
  "external_sku" : { },
  "description" : { },
  "suggest_autocomplete_all" : { },
  "title" : { },
  "holiday" : { },
  "artist_ids" : { },
  "category_id" : { },
  "price" : { },
  "gift_box" : { },
  "api_link" : { },
  "id" : { },
  "sku" : { },
  "last_updated_source" : { },
  "architecture" : { },
  "timestamp" : { },
  "glass" : { },
  "last_updated" : { },
  "is_active" : { },
  "image_url" : { },
  "title_sort" : { },
  "priority" : { },
  "aic_collection" : { },
  "suggest_autocomplete_boosted" : { },
  "api_model" : { },
  "web_url" : { },
  "parent_id" : { }
}, {
  "external_sku" : { },
  "description" : { },
  "suggest_autocomplete_all" : { },
  "title" : { },
  "holiday" : { },
  "artist_ids" : { },
  "category_id" : { },
  "price" : { },
  "gift_box" : { },
  "api_link" : { },
  "id" : { },
  "sku" : { },
  "last_updated_source" : { },
  "architecture" : { },
  "timestamp" : { },
  "glass" : { },
  "last_updated" : { },
  "is_active" : { },
  "image_url" : { },
  "title_sort" : { },
  "priority" : { },
  "aic_collection" : { },
  "suggest_autocomplete_boosted" : { },
  "api_model" : { },
  "web_url" : { },
  "parent_id" : { }
} ]}]

     - returns: RequestBuilder<[Product]> 
     */
    open class func productsGetWithRequestBuilder() -> RequestBuilder<[Product]> {
        let path = "/products"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[Product]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     A single product by the given identifier.
     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func productsIdGet(_id: String, completion: @escaping ((_ data: [Product]?,_ error: Error?) -> Void)) {
        productsIdGetWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     A single product by the given identifier.
     - GET /products/{id}
     - examples: [{contentType=application/json, example=[ {
  "external_sku" : { },
  "description" : { },
  "suggest_autocomplete_all" : { },
  "title" : { },
  "holiday" : { },
  "artist_ids" : { },
  "category_id" : { },
  "price" : { },
  "gift_box" : { },
  "api_link" : { },
  "id" : { },
  "sku" : { },
  "last_updated_source" : { },
  "architecture" : { },
  "timestamp" : { },
  "glass" : { },
  "last_updated" : { },
  "is_active" : { },
  "image_url" : { },
  "title_sort" : { },
  "priority" : { },
  "aic_collection" : { },
  "suggest_autocomplete_boosted" : { },
  "api_model" : { },
  "web_url" : { },
  "parent_id" : { }
}, {
  "external_sku" : { },
  "description" : { },
  "suggest_autocomplete_all" : { },
  "title" : { },
  "holiday" : { },
  "artist_ids" : { },
  "category_id" : { },
  "price" : { },
  "gift_box" : { },
  "api_link" : { },
  "id" : { },
  "sku" : { },
  "last_updated_source" : { },
  "architecture" : { },
  "timestamp" : { },
  "glass" : { },
  "last_updated" : { },
  "is_active" : { },
  "image_url" : { },
  "title_sort" : { },
  "priority" : { },
  "aic_collection" : { },
  "suggest_autocomplete_boosted" : { },
  "api_model" : { },
  "web_url" : { },
  "parent_id" : { }
} ]}]
     - parameter _id: (path)  

     - returns: RequestBuilder<[Product]> 
     */
    open class func productsIdGetWithRequestBuilder(_id: String) -> RequestBuilder<[Product]> {
        var path = "/products/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[Product]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Search products data in the aggregator. 
     - parameter q: (query) Your search query (optional)     - parameter query: (query) For complex queries, you can pass Elasticsearch domain syntax queries here (optional)     - parameter sort: (query) Used in conjunction with &#x60;query&#x60; (optional)     - parameter from: (query) Starting point of results. Pagination via Elasticsearch conventions (optional)     - parameter size: (query) Number of results to return. Pagination via Elasticsearch conventions (optional)     - parameter facets: (query) A comma-separated list of &#x27;count&#x27; aggregation facets to include in the results. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func productsSearchGet(q: String? = nil, query: String? = nil, sort: String? = nil, from: Int? = nil, size: Int? = nil, facets: String? = nil, completion: @escaping ((_ data: [SearchResult]?,_ error: Error?) -> Void)) {
        productsSearchGetWithRequestBuilder(q: q, query: query, sort: sort, from: from, size: size, facets: facets).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Search products data in the aggregator. 
     - GET /products/search
     - examples: [{contentType=application/json, example=[ {
  "api_id" : { },
  "thumbnail" : { },
  "api_model" : { },
  "is_boosted" : { },
  "api_link" : { },
  "id" : { },
  "_score" : { },
  "title" : { },
  "timestamp" : { }
}, {
  "api_id" : { },
  "thumbnail" : { },
  "api_model" : { },
  "is_boosted" : { },
  "api_link" : { },
  "id" : { },
  "_score" : { },
  "title" : { },
  "timestamp" : { }
} ]}]
     - parameter q: (query) Your search query (optional)     - parameter query: (query) For complex queries, you can pass Elasticsearch domain syntax queries here (optional)     - parameter sort: (query) Used in conjunction with &#x60;query&#x60; (optional)     - parameter from: (query) Starting point of results. Pagination via Elasticsearch conventions (optional)     - parameter size: (query) Number of results to return. Pagination via Elasticsearch conventions (optional)     - parameter facets: (query) A comma-separated list of &#x27;count&#x27; aggregation facets to include in the results. (optional)

     - returns: RequestBuilder<[SearchResult]> 
     */
    open class func productsSearchGetWithRequestBuilder(q: String? = nil, query: String? = nil, sort: String? = nil, from: Int? = nil, size: Int? = nil, facets: String? = nil) -> RequestBuilder<[SearchResult]> {
        let path = "/products/search"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "q": q, 
                        "query": query, 
                        "sort": sort, 
                        "from": from, 
                        "size": size, 
                        "facets": facets
        ])

        let requestBuilder: RequestBuilder<[SearchResult]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
