//
// SectionsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class SectionsAPI {
    /**
     A list of all sections sorted by last updated date in descending order.

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func sectionsGet(completion: @escaping ((_ data: [Section]?,_ error: Error?) -> Void)) {
        sectionsGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     A list of all sections sorted by last updated date in descending order.
     - GET /sections
     - examples: [{contentType=application/json, example=[ {
  "generic_page_id" : { },
  "last_updated" : { },
  "weight" : { },
  "accession" : { },
  "suggest_autocomplete_all" : { },
  "title" : { },
  "content" : { },
  "revision" : { },
  "publication_id" : { },
  "suggest_autocomplete_boosted" : { },
  "api_model" : { },
  "web_url" : { },
  "parent_id" : { },
  "api_link" : { },
  "publication_title" : { },
  "id" : { },
  "source_id" : { },
  "artwork_id" : { },
  "last_updated_source" : { },
  "timestamp" : { }
}, {
  "generic_page_id" : { },
  "last_updated" : { },
  "weight" : { },
  "accession" : { },
  "suggest_autocomplete_all" : { },
  "title" : { },
  "content" : { },
  "revision" : { },
  "publication_id" : { },
  "suggest_autocomplete_boosted" : { },
  "api_model" : { },
  "web_url" : { },
  "parent_id" : { },
  "api_link" : { },
  "publication_title" : { },
  "id" : { },
  "source_id" : { },
  "artwork_id" : { },
  "last_updated_source" : { },
  "timestamp" : { }
} ]}]

     - returns: RequestBuilder<[Section]> 
     */
    open class func sectionsGetWithRequestBuilder() -> RequestBuilder<[Section]> {
        let path = "/sections"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[Section]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     A single section by the given identifier.
     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func sectionsIdGet(_id: String, completion: @escaping ((_ data: [Section]?,_ error: Error?) -> Void)) {
        sectionsIdGetWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     A single section by the given identifier.
     - GET /sections/{id}
     - examples: [{contentType=application/json, example=[ {
  "generic_page_id" : { },
  "last_updated" : { },
  "weight" : { },
  "accession" : { },
  "suggest_autocomplete_all" : { },
  "title" : { },
  "content" : { },
  "revision" : { },
  "publication_id" : { },
  "suggest_autocomplete_boosted" : { },
  "api_model" : { },
  "web_url" : { },
  "parent_id" : { },
  "api_link" : { },
  "publication_title" : { },
  "id" : { },
  "source_id" : { },
  "artwork_id" : { },
  "last_updated_source" : { },
  "timestamp" : { }
}, {
  "generic_page_id" : { },
  "last_updated" : { },
  "weight" : { },
  "accession" : { },
  "suggest_autocomplete_all" : { },
  "title" : { },
  "content" : { },
  "revision" : { },
  "publication_id" : { },
  "suggest_autocomplete_boosted" : { },
  "api_model" : { },
  "web_url" : { },
  "parent_id" : { },
  "api_link" : { },
  "publication_title" : { },
  "id" : { },
  "source_id" : { },
  "artwork_id" : { },
  "last_updated_source" : { },
  "timestamp" : { }
} ]}]
     - parameter _id: (path)  

     - returns: RequestBuilder<[Section]> 
     */
    open class func sectionsIdGetWithRequestBuilder(_id: String) -> RequestBuilder<[Section]> {
        var path = "/sections/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[Section]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Search sections data in the aggregator. 
     - parameter q: (query) Your search query (optional)     - parameter query: (query) For complex queries, you can pass Elasticsearch domain syntax queries here (optional)     - parameter sort: (query) Used in conjunction with &#x60;query&#x60; (optional)     - parameter from: (query) Starting point of results. Pagination via Elasticsearch conventions (optional)     - parameter size: (query) Number of results to return. Pagination via Elasticsearch conventions (optional)     - parameter facets: (query) A comma-separated list of &#x27;count&#x27; aggregation facets to include in the results. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func sectionsSearchGet(q: String? = nil, query: String? = nil, sort: String? = nil, from: Int? = nil, size: Int? = nil, facets: String? = nil, completion: @escaping ((_ data: [SearchResult]?,_ error: Error?) -> Void)) {
        sectionsSearchGetWithRequestBuilder(q: q, query: query, sort: sort, from: from, size: size, facets: facets).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Search sections data in the aggregator. 
     - GET /sections/search
     - examples: [{contentType=application/json, example=[ {
  "api_id" : { },
  "thumbnail" : { },
  "api_model" : { },
  "is_boosted" : { },
  "api_link" : { },
  "id" : { },
  "_score" : { },
  "title" : { },
  "timestamp" : { }
}, {
  "api_id" : { },
  "thumbnail" : { },
  "api_model" : { },
  "is_boosted" : { },
  "api_link" : { },
  "id" : { },
  "_score" : { },
  "title" : { },
  "timestamp" : { }
} ]}]
     - parameter q: (query) Your search query (optional)     - parameter query: (query) For complex queries, you can pass Elasticsearch domain syntax queries here (optional)     - parameter sort: (query) Used in conjunction with &#x60;query&#x60; (optional)     - parameter from: (query) Starting point of results. Pagination via Elasticsearch conventions (optional)     - parameter size: (query) Number of results to return. Pagination via Elasticsearch conventions (optional)     - parameter facets: (query) A comma-separated list of &#x27;count&#x27; aggregation facets to include in the results. (optional)

     - returns: RequestBuilder<[SearchResult]> 
     */
    open class func sectionsSearchGetWithRequestBuilder(q: String? = nil, query: String? = nil, sort: String? = nil, from: Int? = nil, size: Int? = nil, facets: String? = nil) -> RequestBuilder<[SearchResult]> {
        let path = "/sections/search"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "q": q, 
                        "query": query, 
                        "sort": sort, 
                        "from": from, 
                        "size": size, 
                        "facets": facets
        ])

        let requestBuilder: RequestBuilder<[SearchResult]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
