//
// SelectionsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class SelectionsAPI {
    /**
     A list of all selections sorted by last updated date in descending order.

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func selectionsGet(completion: @escaping ((_ data: [Selection]?,_ error: Error?) -> Void)) {
        selectionsGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     A list of all selections sorted by last updated date in descending order.
     - GET /selections
     - examples: [{contentType=application/json, example=[ {
  "last_updated" : { },
  "published" : { },
  "suggest_autocomplete_all" : { },
  "title" : { },
  "publish_end_date" : { },
  "suggest_autocomplete_boosted" : { },
  "api_model" : { },
  "publish_start_date" : { },
  "short_copy" : { },
  "api_link" : { },
  "id" : { },
  "copy" : { },
  "last_updated_source" : { },
  "timestamp" : { }
}, {
  "last_updated" : { },
  "published" : { },
  "suggest_autocomplete_all" : { },
  "title" : { },
  "publish_end_date" : { },
  "suggest_autocomplete_boosted" : { },
  "api_model" : { },
  "publish_start_date" : { },
  "short_copy" : { },
  "api_link" : { },
  "id" : { },
  "copy" : { },
  "last_updated_source" : { },
  "timestamp" : { }
} ]}]

     - returns: RequestBuilder<[Selection]> 
     */
    open class func selectionsGetWithRequestBuilder() -> RequestBuilder<[Selection]> {
        let path = "/selections"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[Selection]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     A single selection by the given identifier.
     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func selectionsIdGet(_id: String, completion: @escaping ((_ data: [Selection]?,_ error: Error?) -> Void)) {
        selectionsIdGetWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     A single selection by the given identifier.
     - GET /selections/{id}
     - examples: [{contentType=application/json, example=[ {
  "last_updated" : { },
  "published" : { },
  "suggest_autocomplete_all" : { },
  "title" : { },
  "publish_end_date" : { },
  "suggest_autocomplete_boosted" : { },
  "api_model" : { },
  "publish_start_date" : { },
  "short_copy" : { },
  "api_link" : { },
  "id" : { },
  "copy" : { },
  "last_updated_source" : { },
  "timestamp" : { }
}, {
  "last_updated" : { },
  "published" : { },
  "suggest_autocomplete_all" : { },
  "title" : { },
  "publish_end_date" : { },
  "suggest_autocomplete_boosted" : { },
  "api_model" : { },
  "publish_start_date" : { },
  "short_copy" : { },
  "api_link" : { },
  "id" : { },
  "copy" : { },
  "last_updated_source" : { },
  "timestamp" : { }
} ]}]
     - parameter _id: (path)  

     - returns: RequestBuilder<[Selection]> 
     */
    open class func selectionsIdGetWithRequestBuilder(_id: String) -> RequestBuilder<[Selection]> {
        var path = "/selections/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[Selection]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Search selections data in the aggregator. 
     - parameter q: (query) Your search query (optional)     - parameter query: (query) For complex queries, you can pass Elasticsearch domain syntax queries here (optional)     - parameter sort: (query) Used in conjunction with &#x60;query&#x60; (optional)     - parameter from: (query) Starting point of results. Pagination via Elasticsearch conventions (optional)     - parameter size: (query) Number of results to return. Pagination via Elasticsearch conventions (optional)     - parameter facets: (query) A comma-separated list of &#x27;count&#x27; aggregation facets to include in the results. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func selectionsSearchGet(q: String? = nil, query: String? = nil, sort: String? = nil, from: Int? = nil, size: Int? = nil, facets: String? = nil, completion: @escaping ((_ data: [SearchResult]?,_ error: Error?) -> Void)) {
        selectionsSearchGetWithRequestBuilder(q: q, query: query, sort: sort, from: from, size: size, facets: facets).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Search selections data in the aggregator. 
     - GET /selections/search
     - examples: [{contentType=application/json, example=[ {
  "api_id" : { },
  "thumbnail" : { },
  "api_model" : { },
  "is_boosted" : { },
  "api_link" : { },
  "id" : { },
  "_score" : { },
  "title" : { },
  "timestamp" : { }
}, {
  "api_id" : { },
  "thumbnail" : { },
  "api_model" : { },
  "is_boosted" : { },
  "api_link" : { },
  "id" : { },
  "_score" : { },
  "title" : { },
  "timestamp" : { }
} ]}]
     - parameter q: (query) Your search query (optional)     - parameter query: (query) For complex queries, you can pass Elasticsearch domain syntax queries here (optional)     - parameter sort: (query) Used in conjunction with &#x60;query&#x60; (optional)     - parameter from: (query) Starting point of results. Pagination via Elasticsearch conventions (optional)     - parameter size: (query) Number of results to return. Pagination via Elasticsearch conventions (optional)     - parameter facets: (query) A comma-separated list of &#x27;count&#x27; aggregation facets to include in the results. (optional)

     - returns: RequestBuilder<[SearchResult]> 
     */
    open class func selectionsSearchGetWithRequestBuilder(q: String? = nil, query: String? = nil, sort: String? = nil, from: Int? = nil, size: Int? = nil, facets: String? = nil) -> RequestBuilder<[SearchResult]> {
        let path = "/selections/search"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "q": q, 
                        "query": query, 
                        "sort": sort, 
                        "from": from, 
                        "size": size, 
                        "facets": facets
        ])

        let requestBuilder: RequestBuilder<[SearchResult]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
