//
// VideosAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class VideosAPI {
    /**
     A list of all videos sorted by last updated date in descending order.

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func videosGet(completion: @escaping ((_ data: [Video]?,_ error: Error?) -> Void)) {
        videosGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     A list of all videos sorted by last updated date in descending order.
     - GET /videos
     - examples: [{contentType=application/json, example=[ {
  "last_updated" : { },
  "is_multimedia_resource" : { },
  "lake_guid" : { },
  "description" : { },
  "suggest_autocomplete_all" : { },
  "title" : { },
  "type" : { },
  "content" : { },
  "content_e_tag" : { },
  "suggest_autocomplete_boosted" : { },
  "api_model" : { },
  "copyright_notice" : { },
  "alt_text" : { },
  "api_link" : { },
  "artwork_titles" : { },
  "content_modified_at" : { },
  "artwork_ids" : { },
  "id" : { },
  "is_educational_resource" : { },
  "last_updated_source" : { },
  "is_teacher_resource" : { },
  "timestamp" : { }
}, {
  "last_updated" : { },
  "is_multimedia_resource" : { },
  "lake_guid" : { },
  "description" : { },
  "suggest_autocomplete_all" : { },
  "title" : { },
  "type" : { },
  "content" : { },
  "content_e_tag" : { },
  "suggest_autocomplete_boosted" : { },
  "api_model" : { },
  "copyright_notice" : { },
  "alt_text" : { },
  "api_link" : { },
  "artwork_titles" : { },
  "content_modified_at" : { },
  "artwork_ids" : { },
  "id" : { },
  "is_educational_resource" : { },
  "last_updated_source" : { },
  "is_teacher_resource" : { },
  "timestamp" : { }
} ]}]

     - returns: RequestBuilder<[Video]> 
     */
    open class func videosGetWithRequestBuilder() -> RequestBuilder<[Video]> {
        let path = "/videos"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[Video]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     A single video by the given identifier. {id} is the identifier from our collections management system.
     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func videosIdGet(_id: String, completion: @escaping ((_ data: [Video]?,_ error: Error?) -> Void)) {
        videosIdGetWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     A single video by the given identifier. {id} is the identifier from our collections management system.
     - GET /videos/{id}
     - examples: [{contentType=application/json, example=[ {
  "last_updated" : { },
  "is_multimedia_resource" : { },
  "lake_guid" : { },
  "description" : { },
  "suggest_autocomplete_all" : { },
  "title" : { },
  "type" : { },
  "content" : { },
  "content_e_tag" : { },
  "suggest_autocomplete_boosted" : { },
  "api_model" : { },
  "copyright_notice" : { },
  "alt_text" : { },
  "api_link" : { },
  "artwork_titles" : { },
  "content_modified_at" : { },
  "artwork_ids" : { },
  "id" : { },
  "is_educational_resource" : { },
  "last_updated_source" : { },
  "is_teacher_resource" : { },
  "timestamp" : { }
}, {
  "last_updated" : { },
  "is_multimedia_resource" : { },
  "lake_guid" : { },
  "description" : { },
  "suggest_autocomplete_all" : { },
  "title" : { },
  "type" : { },
  "content" : { },
  "content_e_tag" : { },
  "suggest_autocomplete_boosted" : { },
  "api_model" : { },
  "copyright_notice" : { },
  "alt_text" : { },
  "api_link" : { },
  "artwork_titles" : { },
  "content_modified_at" : { },
  "artwork_ids" : { },
  "id" : { },
  "is_educational_resource" : { },
  "last_updated_source" : { },
  "is_teacher_resource" : { },
  "timestamp" : { }
} ]}]
     - parameter _id: (path)  

     - returns: RequestBuilder<[Video]> 
     */
    open class func videosIdGetWithRequestBuilder(_id: String) -> RequestBuilder<[Video]> {
        var path = "/videos/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[Video]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Search videos data in the aggregator. 
     - parameter q: (query) Your search query (optional)     - parameter query: (query) For complex queries, you can pass Elasticsearch domain syntax queries here (optional)     - parameter sort: (query) Used in conjunction with &#x60;query&#x60; (optional)     - parameter from: (query) Starting point of results. Pagination via Elasticsearch conventions (optional)     - parameter size: (query) Number of results to return. Pagination via Elasticsearch conventions (optional)     - parameter facets: (query) A comma-separated list of &#x27;count&#x27; aggregation facets to include in the results. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func videosSearchGet(q: String? = nil, query: String? = nil, sort: String? = nil, from: Int? = nil, size: Int? = nil, facets: String? = nil, completion: @escaping ((_ data: [SearchResult]?,_ error: Error?) -> Void)) {
        videosSearchGetWithRequestBuilder(q: q, query: query, sort: sort, from: from, size: size, facets: facets).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Search videos data in the aggregator. 
     - GET /videos/search
     - examples: [{contentType=application/json, example=[ {
  "api_id" : { },
  "thumbnail" : { },
  "api_model" : { },
  "is_boosted" : { },
  "api_link" : { },
  "id" : { },
  "_score" : { },
  "title" : { },
  "timestamp" : { }
}, {
  "api_id" : { },
  "thumbnail" : { },
  "api_model" : { },
  "is_boosted" : { },
  "api_link" : { },
  "id" : { },
  "_score" : { },
  "title" : { },
  "timestamp" : { }
} ]}]
     - parameter q: (query) Your search query (optional)     - parameter query: (query) For complex queries, you can pass Elasticsearch domain syntax queries here (optional)     - parameter sort: (query) Used in conjunction with &#x60;query&#x60; (optional)     - parameter from: (query) Starting point of results. Pagination via Elasticsearch conventions (optional)     - parameter size: (query) Number of results to return. Pagination via Elasticsearch conventions (optional)     - parameter facets: (query) A comma-separated list of &#x27;count&#x27; aggregation facets to include in the results. (optional)

     - returns: RequestBuilder<[SearchResult]> 
     */
    open class func videosSearchGetWithRequestBuilder(q: String? = nil, query: String? = nil, sort: String? = nil, from: Int? = nil, size: Int? = nil, facets: String? = nil) -> RequestBuilder<[SearchResult]> {
        let path = "/videos/search"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "q": q, 
                        "query": query, 
                        "sort": sort, 
                        "from": from, 
                        "size": size, 
                        "facets": facets
        ])

        let requestBuilder: RequestBuilder<[SearchResult]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
